package com.devs.gama.stu.enums;

import java.util.Arrays;

import com.devs.gama.stu.exceptions.CallNotFoundException;

public enum FuncoesViewsTables {

	TABELA_PROFESSOR("PROFESSOR"),

	TABELA_ALUNO("ALUNO"),

	TABELA_FORMA_PAGAMENTO("FORMA_PAGAMENTO"),

	TABELA_MENSALIDADE_ABERTA("MENSALIDADE_ABERTA"),

	TABELA_MENSALIDADE_COBRADA("MENSALIDADE_COBRADA"),

	FUNCAO_CADASTRAR_PROFESSOR("CADASTRAR_PROFESSOR"),

	FUNCAO_ALTERAR_SENHA_PROFESSOR("ALTERAR_SENHA_PROFESSOR"),

	FUNCAO_CADASTRAR_ALUNO("CADASTRAR_ALUNO"),

	FUNCAO_CADASTRAR_ALUNO_SEM_MENSALIDADE("CADASTRAR_ALUNO_SEM_MENSALIDADE"),

	FUNCAO_EDITAR_ALUNO("EDITAR_ALUNO"),

	FUNCAO_EDITAR_PROFESSOR("EDITAR_PROFESSOR"),

	FUNCAO_EDITAR_MENSALIDADE_ABERTA("EDITAR_MENSALIDADE_ABERTA"),

	FUNCAO_GERAR_MENSALIDADE_ABERTA("GERAR_MENSALIDADE_ABERTA"),

	FUNCAO_GERAR_CONFIRMAR_PAGAMENTO("CONFIRMAR_PAGAMENTO"),

	FUNCAO_CADASTRAR_FORMA_PAGAMENTO("CADASTRAR_FORMA_PAGAMENTO"),

	FUNCAO_EDITAR_FORMA_PAGAMENTO("EDITAR_FORMA_PAGAMENTO"),

	FUNCAO_DELETE_FORMA_PAGAMENTO("DELETE_FORMA_PAGAMENTO"),

	FUNCAO_ATUALIZAR_STATUS("ATUALIZAR_STATUS"),

	FUNCAO_INATIVAR_ALUNO("INATIVAR_ALUNO"),

	FUNCAO_ATIVAR_ALUNO("ATIVAR_ALUNO"),

	FUNCAO_INATIVAR_PROFESSOR("INATIVAR_PROFESSOR"),
	
	FUNCAO_ATIVAR_PROFESSOR("ATIVAR_PROFESSOR"),

	VIEW_PROFESSOR("VIEW_PROFESSOR"),

	VIEW_ALUNO_DE_PROFESSOR("VIEW_ALUNO_DE_PROFESSOR"),

	VIEW_FORMAS_PAGAMENTO("VIEW_FORMAS_PAGAMENTO"),

	VIEW_ALUNO_MENSALIDADES_COBRADAS("VIEW_ALUNO_MENSALIDADES_COBRADAS"),

	VIEW_ALUNO_MENSALIDADE_ABERTA("VIEW_ALUNO_MENSALIDADE_ABERTA");

	public final String value;

	FuncoesViewsTables(String value) {
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}

	public static FuncoesViewsTables valueOfProceduresViews(String value) {
		return Arrays.asList(FuncoesViewsTables.values()).stream().filter(s -> s.getValue().equalsIgnoreCase(value))
				.findFirst()
				.orElseThrow(() -> new CallNotFoundException("Procedure, View or Table not found: " + value));
	}
}
